// packages/adapters/react/src/FilePreview.tsx
import React, { useEffect, useImperativeHandle, useRef, forwardRef, memo } from 'react';
import {
  FilePreviewViewer,
  type FileSource,
  type PreviewPlugin,
  type PreviewViewerOptions,
  type PreviewInstance,
} from '@patel.sumit51/core';

export interface FilePreviewProps {
  src: FileSource;
  plugins?: PreviewPlugin[];
  options?: PreviewViewerOptions;
  onLoading?: () => void;
  onLoaded?: (data: unknown) => void;
  onError?: (error: Error) => void;
  onPageChange?: (data: unknown) => void;
  onZoomChange?: (data: unknown) => void;
  className?: string;
  classname?: string;
  style?: React.CSSProperties;
}

export interface FilePreviewHandle {
  getInstance: () => PreviewInstance | null;
  getViewer: () => FilePreviewViewer | null;
  resetZoom: () => void;
  fitToPage: () => void;
  setShowToolbar: (show: boolean) => void;
  toggleToolbar: () => void;
  setShowFileName: (show: boolean) => void;
  destroy: () => void;
}

export const FilePreview = memo(forwardRef<FilePreviewHandle, FilePreviewProps>(
  (
    {
      src,
      plugins = [],
      options = {},
      onLoading,
      onLoaded,
      onError,
      onPageChange,
      onZoomChange,
      className,
      classname,
      style,
    },
    ref
  ) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const viewerRef = useRef<FilePreviewViewer | null>(null);
    const instanceRef = useRef<PreviewInstance | null>(null);

    useImperativeHandle(ref, () => ({
      getInstance: () => instanceRef.current,
      getViewer: () => viewerRef.current,
      resetZoom: () => viewerRef.current?.resetZoom(),
      fitToPage: () => viewerRef.current?.fitToPage(),
      setShowToolbar: (show: boolean) => viewerRef.current?.setShowToolbar(show),
      toggleToolbar: () => viewerRef.current?.toggleToolbar(),
      setShowFileName: (show: boolean) => viewerRef.current?.setShowFileName(show),
      destroy: () => viewerRef.current?.destroy(),
    }));

    // Initialize viewer on mount
    useEffect(() => {
      const viewer = new FilePreviewViewer();
      plugins.forEach(p => viewer.registerPlugin(p));
      viewerRef.current = viewer;

      const unsubs: Array<() => void> = [];
      if (onLoading) unsubs.push(viewer.on('loading', onLoading));
      if (onLoaded) unsubs.push(viewer.on('loaded', onLoaded));
      if (onError) unsubs.push(viewer.on('error', (e: unknown) => onError(e instanceof Error ? e : new Error(String(e)))));
      if (onPageChange) unsubs.push(viewer.on('page-change', onPageChange));
      if (onZoomChange) unsubs.push(viewer.on('zoom-change', onZoomChange));

      return () => {
        unsubs.forEach(fn => fn());
        viewer.destroy();
        viewerRef.current = null;
        instanceRef.current = null;
      };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // Preview file when src or options change
    useEffect(() => {
      if (!viewerRef.current || !containerRef.current || !src) return;

      const doPreview = async () => {
        try {
          instanceRef.current = await viewerRef.current!.preview(
            containerRef.current!,
            src,
            options
          );
        } catch (error: unknown) {
          if (error instanceof DOMException && error.name === 'AbortError') return;
          if (onError) {
            onError(error instanceof Error ? error : new Error(String(error)));
          }
        }
      };

      doPreview();
    }, [src, options, onError]);

    const resolvedClassName = [
      className,
      classname,
      options?.className,
      (options as any)?.classname,
    ]
      .filter(Boolean)
      .join(' ') || undefined;

    return (
      <div
        ref={containerRef}
        className={resolvedClassName}
        style={{ width: '100%', height: '100%', position: 'relative', overflow: 'hidden', ...style }}
      />
    );
  }
));

FilePreview.displayName = 'FilePreview';

// packages/adapters/angular/src/file-preview.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  ViewChild,
  OnInit,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  NgZone,
  ChangeDetectionStrategy,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  FilePreviewViewer,
  type FileSource,
  type PreviewPlugin,
  type PreviewViewerOptions,
  type PreviewInstance,
} from '@patel.sumit51/core';

@Component({
  selector: 'fp-file-preview',
  standalone: true,
  imports: [CommonModule],
  template: `<div #container [class]="getContainerClass()" [style.width]="'100%'" [style.height]="'100%'" [style.position]="'relative'" [style.overflow]="'hidden'"></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FilePreviewComponent implements OnInit, OnChanges, OnDestroy {
  @Input({ required: true }) src!: FileSource;
  @Input() plugins: PreviewPlugin[] = [];
  @Input() options: PreviewViewerOptions = {};
  @Input() className?: string;
  @Input() classname?: string;

  @Output() loading = new EventEmitter<void>();
  @Output() loaded = new EventEmitter<unknown>();
  @Output() error = new EventEmitter<Error>();
  @Output() pageChange = new EventEmitter<unknown>();
  @Output() zoomChange = new EventEmitter<unknown>();

  @ViewChild('container', { static: true }) container!: ElementRef<HTMLDivElement>;

  getContainerClass(): string {
    return [
      this.className,
      this.classname,
      this.options?.className,
      (this.options as any)?.classname,
    ]
      .filter(Boolean)
      .join(' ');
  }

  private viewer: FilePreviewViewer | null = null;
  private instance: PreviewInstance | null = null;

  constructor(private ngZone: NgZone) {}

  ngOnInit(): void {
    const viewer = new FilePreviewViewer();
    this.plugins.forEach(p => viewer.registerPlugin(p));
    this.viewer = viewer;

    viewer.on('loading', () => {
      this.ngZone.run(() => this.loading.emit());
    });
    viewer.on('loaded', (data: unknown) => {
      this.ngZone.run(() => this.loaded.emit(data));
    });
    viewer.on('error', (e: unknown) => {
      this.ngZone.run(() => this.error.emit(e instanceof Error ? e : new Error(String(e))));
    });
    viewer.on('page-change', (data: unknown) => {
      this.ngZone.run(() => this.pageChange.emit(data));
    });
    viewer.on('zoom-change', (data: unknown) => {
      this.ngZone.run(() => this.zoomChange.emit(data));
    });

    this.render();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if ((changes['src'] || changes['options']) && !changes['src']?.isFirstChange()) {
      this.render();
    }
  }

  private render(): void {
    if (!this.viewer || !this.src || !this.container) return;

    this.ngZone.runOutsideAngular(async () => {
      try {
        this.instance = await this.viewer!.preview(
          this.container.nativeElement,
          this.src,
          this.options
        );
      } catch (err: unknown) {
        if (err instanceof DOMException && err.name === 'AbortError') return;
        this.ngZone.run(() => {
          this.error.emit(err instanceof Error ? err : new Error(String(err)));
        });
      }
    });
  }

  ngOnDestroy(): void {
    if (this.viewer) {
      this.viewer.destroy();
      this.viewer = null;
      this.instance = null;
    }
  }

  public getInstance(): PreviewInstance | null {
    return this.instance;
  }

  public getViewer(): FilePreviewViewer | null {
    return this.viewer;
  }

  public setShowToolbar(show: boolean): void {
    this.viewer?.setShowToolbar(show);
  }

  public toggleToolbar(): void {
    this.viewer?.toggleToolbar();
  }

  public setShowFileName(show: boolean): void {
    this.viewer?.setShowFileName(show);
  }
}
